name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v[0-9]+.*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-linux:
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install OpenCV
        run: sudo apt-get update && sudo apt-get install -y libopencv-dev pkg-config
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: kensa
          token: ${{ secrets.GITHUB_TOKEN }}
          target: x86_64-unknown-linux-gnu
          tar: unix
          zip: none

  upload-macos-x64:
    needs: create-release
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Install OpenCV
        run: brew install opencv
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: kensa
          token: ${{ secrets.GITHUB_TOKEN }}
          target: x86_64-apple-darwin
          tar: unix
          zip: none

  upload-macos-arm64:
    needs: create-release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install OpenCV
        run: brew install opencv
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: kensa
          token: ${{ secrets.GITHUB_TOKEN }}
          target: aarch64-apple-darwin
          tar: unix
          zip: none
